Bug fix: allow std 0 in the meta definition of normal_
All other normal variants allow 0.  Looks like a mistake made while
copying the check.  Even the normal_ implementation disagrees:

>>> t = torch.rand(2, 3, device='meta')
>>> t.normal_(mean=4, std=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: normal_ expects std > 0.0, but found std=0
>>>
>>>
>>> t = torch.rand(2, 3)
>>> t.normal_(mean=4, std=0)
tensor([[4., 4., 4.],
        [4., 4., 4.]])

Fixes #69523.